name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        cache: true

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v -buildvcs=false ./...

    - name: Test
      run: go test -v ./...
      
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

  # Create a job for each OS (Windows, macOS, Linux)
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: subenum
            asset_name: subenum-linux-amd64
          - os: windows-latest
            artifact_name: subenum.exe
            asset_name: subenum-windows-amd64.exe
          - os: macos-latest
            artifact_name: subenum
            asset_name: subenum-macos-amd64
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        cache: true
    
    - name: Build
      run: go build -v -buildvcs=false -o ${{ matrix.artifact_name }}
    
    - name: Upload binaries to release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.artifact_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 